// CommonJS, every file is module (by default)
// MODULES - encapsulated code (only share minimum)
const names = require('./4-names')
const sayHI = require('./5-utils')
const data = require('./6-alternative')
require('./7-mind-grenade')
console.log(names)
// sayHI('gabrielle')
sayHI(names.mark)
sayHI(names.bruna)

